"""
Generator for .env.example files.

This module produces formatted, documented .env.example files from
a collection of EnvVariable objects.
"""

from typing import List, Dict, Optional
from collections import defaultdict
from configsmith.models import EnvVariable, VariableCategory


class EnvExampleGenerator:
    """
    Generator for creating formatted .env.example files.
    
    Features:
    - Section headers for categorization
    - Inline documentation comments
    - Sorted alphabetically within sections
    - Source file and line references
    - Type hints and requirement status
    
    Example:
        generator = EnvExampleGenerator()
        content = generator.generate(variables)
        Path(".env.example").write_text(content)
    """
    
    SECTION_SEPARATOR = "# " + "=" * 77
    
    CATEGORY_NAMES = {
        VariableCategory.DATABASE: "DATABASE CONFIGURATION",
        VariableCategory.API: "API CONFIGURATION",
        VariableCategory.APP: "APPLICATION SETTINGS",
        VariableCategory.AUTH: "AUTHENTICATION",
        VariableCategory.LOGGING: "LOGGING",
        VariableCategory.CACHE: "CACHE CONFIGURATION",
        VariableCategory.FEATURE: "FEATURE FLAGS",
        VariableCategory.OTHER: "OTHER SETTINGS",
    }
    
    # Order for sections
    CATEGORY_ORDER = [
        VariableCategory.DATABASE,
        VariableCategory.API,
        VariableCategory.AUTH,
        VariableCategory.APP,
        VariableCategory.CACHE,
        VariableCategory.LOGGING,
        VariableCategory.FEATURE,
        VariableCategory.OTHER,
    ]
    
    def __init__(
        self,
        include_source: bool = True,
        include_type: bool = True,
        group_by_category: bool = True,
        sort_alphabetically: bool = True
    ):
        """
        Initialize the generator.
        
        Args:
            include_source: Include source file/line in comments
            include_type: Include type hints in comments
            group_by_category: Group variables by category
            sort_alphabetically: Sort variables within groups
        """
        self.include_source = include_source
        self.include_type = include_type
        self.group_by_category = group_by_category
        self.sort_alphabetically = sort_alphabetically
    
    def generate(
        self,
        variables: List[EnvVariable],
        preserved_comments: Optional[Dict[str, List[str]]] = None
    ) -> str:
        """
        Generate .env.example content from variables.
        
        Args:
            variables: List of EnvVariable objects
            preserved_comments: Optional dict of variable name to comments to preserve
            
        Returns:
            Formatted .env.example content
        """
        if not variables:
            return "# No environment variables found\n"
        
        if preserved_comments is None:
            preserved_comments = {}
        
        lines: List[str] = []
        
        # Add header
        lines.append("# =============================================================================")
        lines.append("# Environment Configuration")
        lines.append("# Generated by ConfigSmith")
        lines.append("# =============================================================================")
        lines.append("")
        
        if self.group_by_category:
            lines.extend(self._generate_grouped(variables, preserved_comments))
        else:
            lines.extend(self._generate_flat(variables, preserved_comments))
        
        # Ensure file ends with newline
        content = '\n'.join(lines)
        if not content.endswith('\n'):
            content += '\n'
        
        return content
    
    def _generate_grouped(
        self,
        variables: List[EnvVariable],
        preserved_comments: Dict[str, List[str]]
    ) -> List[str]:
        """Generate content grouped by category."""
        lines: List[str] = []
        
        # Group variables by category
        groups: Dict[VariableCategory, List[EnvVariable]] = defaultdict(list)
        for var in variables:
            groups[var.category].append(var)
        
        # Sort within groups
        if self.sort_alphabetically:
            for category in groups:
                groups[category].sort(key=lambda v: v.name)
        
        # Generate sections in order
        first_section = True
        for category in self.CATEGORY_ORDER:
            if category not in groups or not groups[category]:
                continue
            
            if not first_section:
                lines.append("")
            first_section = False
            
            # Section header
            section_name = self.CATEGORY_NAMES.get(category, category.value.upper())
            lines.append(self.SECTION_SEPARATOR)
            lines.append(f"# {section_name}")
            lines.append(self.SECTION_SEPARATOR)
            lines.append("")
            
            # Variables in this section
            for var in groups[category]:
                lines.extend(self._format_variable(var, preserved_comments))
                lines.append("")
        
        return lines
    
    def _generate_flat(
        self,
        variables: List[EnvVariable],
        preserved_comments: Dict[str, List[str]]
    ) -> List[str]:
        """Generate content as flat list."""
        lines: List[str] = []
        
        if self.sort_alphabetically:
            variables = sorted(variables, key=lambda v: v.name)
        
        for var in variables:
            lines.extend(self._format_variable(var, preserved_comments))
            lines.append("")
        
        return lines
    
    def _format_variable(
        self,
        var: EnvVariable,
        preserved_comments: Dict[str, List[str]]
    ) -> List[str]:
        """Format a single variable with comments."""
        lines: List[str] = []
        
        # Check for preserved comments first
        if var.name in preserved_comments:
            for comment in preserved_comments[var.name]:
                lines.append(f"# {comment}")
        else:
            # Generate description comment
            if var.description:
                lines.append(f"# {var.description}")
            
            # Type and required status
            if self.include_type:
                type_info = var.type_hint or "string"
                req_status = "required" if var.required else "optional"
                lines.append(f"# Type: {type_info} ({req_status})")
            
            # Default value info (if has one and is optional)
            if not var.required and var.default_value is not None:
                lines.append(f"# Default: {var.default_value}")
            
            # Security warning for sensitive vars
            if var.is_sensitive:
                lines.append("# Security: Keep secret, do not commit actual value")
            
            # Source location
            if self.include_source and var.source_file:
                source_info = f"# Source: {var.source_file}"
                if var.line_number:
                    source_info += f":{var.line_number}"
                lines.append(source_info)
        
        # The actual key=value line
        value = var.example_value
        lines.append(f"{var.name}={value}")
        
        return lines
    
    def generate_diff(
        self,
        old_content: str,
        new_variables: List[EnvVariable]
    ) -> str:
        """
        Generate a diff-style output showing changes.
        
        Args:
            old_content: Existing .env.example content
            new_variables: New list of variables
            
        Returns:
            Diff-style output
        """
        from configsmith.parser import EnvFileParser
        
        parser = EnvFileParser()
        old_parsed = parser.parse_content(old_content)
        
        old_vars = set(old_parsed.variable_names)
        new_vars = {v.name for v in new_variables}
        
        added = new_vars - old_vars
        removed = old_vars - new_vars
        unchanged = old_vars & new_vars
        
        lines = []
        lines.append("# ConfigSmith Diff Report")
        lines.append("#")
        lines.append(f"# Added:     {len(added)}")
        lines.append(f"# Removed:   {len(removed)}")
        lines.append(f"# Unchanged: {len(unchanged)}")
        lines.append("#")
        
        if added:
            lines.append("# + Added variables:")
            for name in sorted(added):
                lines.append(f"#   + {name}")
        
        if removed:
            lines.append("# - Removed variables:")
            for name in sorted(removed):
                lines.append(f"#   - {name}")
        
        lines.append("")
        
        return '\n'.join(lines)
